<?php
/**
 * @file
 * Temporary home page to test functionality.
 */

// Initializes the autoloader generated by composer.
$loader = require 'vendor/autoload.php';
$loader->addPsr4('Oop\\', __DIR__ . '/src');
$loader->register();

use Oop\Core;
use Symfony\Component\HttpFoundation\Request;

$request = Request::createFromGlobals();

// Our framework is now handling itself the request.
$app = new Core();

$response = $app->handle($request);
$response->send();
