<?php
/**
 * @file
 * Temporary home page to test functionality.
 */

// Initializes the autoloader generated by composer.
$loader = require 'vendor/autoload.php';
$loader->addPsr4('Oop\\', __DIR__ . '/src');
$loader->register();

use Oop\Core;
use Oop\Controller\PostCollectionPage;
use Oop\Controller\HomepagePage;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Routing\Loader\YamlFileLoader;

$request = Request::createFromGlobals();

// Our framework is now handling itself the request.
$app = new Core();
$app->map('/', function () {
  $page = new HomepagePage();
  return $page->homepage();
});
$app->map('/posts/{type}', function ($type) {
  $page = new PostCollectionPage();
  return $page->displayPosts($type);
});

$response = $app->handle($request);
$response->send();
